FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ENV VITE_API_URL=/api
RUN npm run build

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/dist /app/dist
CMD ["sh", "-c", "cp -rp /app/dist/. /app/build/ && echo 'Frontend assets copied.'"]
